services:
  postgres:
    image: postgres:latest
    container_name: postgres_anime
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin_anime
        restart: always
        environment:
          PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
          PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        ports:
          - "${PGADMIN_PORT}:80"
        depends_on:
          - postgres

volumes:
  postgres_data:
